<?php

namespace Pterodactyl\Services\Security;

use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Http;

class OriginProtectionService
{
    private array $cachedCfIps = [];
    private const CF_IPS_V4_URL = 'https://www.cloudflare.com/ips-v4';
    private const CF_IPS_V6_URL = 'https://www.cloudflare.com/ips-v6';

    public function __construct(
        private CloudflareService $cloudflare,
        private ServerProtectionService $server,
    ) {}

    public function getProtectionStatus(string $domain = null): array
    {
        $domain = $domain ?? request()->getHost();
        $originCheck = $this->checkOriginProtection($domain);

        $cfIpsInstalled = $this->isCfIptablesInstalled();
        $tunnelInstalled = $this->isCloudflareTunnelInstalled();
        $directIpBlocked = $this->isDirectIpAccessBlocked();
        $realIpConfigured = $this->isRealIpConfigured();

        return [
            'domain' => $domain,
            'origin_check' => $originCheck,
            'cf_only_iptables' => $cfIpsInstalled,
            'tunnel_installed' => $tunnelInstalled,
            'direct_ip_blocked' => $directIpBlocked,
            'real_ip_configured' => $realIpConfigured,
            'protection_score' => $originCheck['score']
                + ($cfIpsInstalled ? 1 : 0)
                + ($tunnelInstalled ? 2 : 0)
                + ($directIpBlocked ? 1 : 0)
                + ($realIpConfigured ? 1 : 0),
            'max_score' => $originCheck['max_score'] + 5,
        ];
    }

    public function checkOriginProtection(string $domain): array
    {
        $proxyStatus = $this->cloudflare->getDnsProxyStatus($domain);
        $score = ($proxyStatus['proxied'] ?? false) ? 1 : 0;

        return [
            'domain' => $domain,
            'proxied' => $proxyStatus['proxied'] ?? false,
            'real_ip' => $proxyStatus['content'] ?? '',
            'score' => $score,
            'max_score' => 1,
        ];
    }

    public function installCfOnlyIptables(): array
    {
        try {
            $ips = $this->fetchCfIps();
            if (empty($ips['ipv4']) && empty($ips['ipv6'])) {
                return ['success' => false, 'error' => 'Could not fetch Cloudflare IPs'];
            }
            $this->server->flushIptables();
            $this->server->allowLoopback();
            $this->server->allowEstablished();
            shell_exec('iptables -A INPUT -p tcp --dport 22 -j ACCEPT 2>&1');

            foreach ($ips['ipv4'] ?? [] as $ip) {
                $ip = trim($ip);
                if (!empty($ip)) {
                    shell_exec("iptables -A INPUT -p tcp -s {$ip} --dport 80 -j ACCEPT 2>&1");
                    shell_exec("iptables -A INPUT -p tcp -s {$ip} --dport 443 -j ACCEPT 2>&1");
                }
            }
            shell_exec('iptables -A INPUT -p tcp --dport 80 -j DROP 2>&1');
            shell_exec('iptables -A INPUT -p tcp --dport 443 -j DROP 2>&1');
            Log::info('OriginProtection: CF-only iptables rules installed');
            return ['success' => true, 'ipv4_count' => count($ips['ipv4'] ?? []), 'ipv6_count' => count($ips['ipv6'] ?? [])];
        } catch (\Exception $e) {
            return ['success' => false, 'error' => $e->getMessage()];
        }
    }

    public function blockDirectIpAccess(): array
    {
        try {
            $ips = $this->getServerIps();
            $results = [];
            foreach ($ips as $ip) {
                $r = $this->server->blockIpIptables($ip);
                $results[] = ['ip' => $ip, 'success' => $r['success'] ?? false];
            }
            shell_exec('iptables -A INPUT -p tcp --dport 80 -m state --state NEW -m recent --name DIRECTIP --set 2>&1');
            shell_exec('iptables -A INPUT -p tcp --dport 80 -m state --state NEW -m recent --name DIRECTIP --update --seconds 10 --hitcount 1 -j DROP 2>&1');
            Log::info('OriginProtection: Direct IP access blocked');
            return ['success' => true, 'results' => $results];
        } catch (\Exception $e) {
            return ['success' => false, 'error' => $e->getMessage()];
        }
    }

    public function installRealIpConfig(): array
    {
        $cfIps = $this->fetchCfIps();
        if (empty($cfIps['ipv4'])) {
            return ['success' => false, 'error' => 'Could not fetch CF IPs'];
        }
        $setRealIp = "real_ip_header CF-Connecting-IP;\nreal_ip_recursive on;\n";
        foreach ($cfIps['ipv4'] ?? [] as $ip) {
            $ip = trim($ip);
            if (!empty($ip)) $setRealIp .= "set_real_ip_from {$ip};\n";
        }
        $nginxConfig = "# Cloudflare Real IP Configuration\n# Generated by Royal Security\n\n{$setRealIp}\n";
        $paths = ['/etc/nginx/cloudflare.conf', '/etc/nginx/conf.d/cloudflare.conf'];
        $written = false;
        foreach ($paths as $path) {
            try {
                if (is_dir(dirname($path))) {
                    file_put_contents($path, $nginxConfig);
                    $written = $path;
                }
            } catch (\Exception $e) { continue; }
        }
        if ($written) {
            $reload = shell_exec('nginx -t 2>&1');
            if (str_contains($reload ?? '', 'test is successful')) {
                shell_exec('systemctl reload nginx 2>&1');
                return ['success' => true, 'path' => $written, 'nginx_reload' => true];
            }
            return ['success' => true, 'path' => $written, 'nginx_reload' => false];
        }
        return ['success' => false, 'error' => 'Could not write to any nginx config path'];
    }

    public function enableFullSslStrict(): array
    {
        if (!$this->cloudflare->enabled()) {
            return ['success' => false, 'error' => 'Cloudflare not configured'];
        }
        return [
            'ssl' => $this->cloudflare->setSsl('full'),
            'always_https' => $this->cloudflare->setAlwaysUseHttps(true),
            'tls' => $this->cloudflare->setMinimumTlsVersion('1.2'),
        ];
    }

    public function enableOrangeCloud(string $domain = null): array
    {
        if (!$this->cloudflare->enabled()) {
            return ['success' => false, 'error' => 'Cloudflare not configured'];
        }
        $domain = $domain ?? request()->getHost();
        return $this->cloudflare->setDnsProxy($domain, true);
    }

    public function getServerIps(): array
    {
        $ips = [];
        $hostname = gethostname();
        $raw = shell_exec("hostname -I 2>&1");
        if ($raw) {
            $parts = explode(' ', trim($raw));
            foreach ($parts as $part) {
                $part = trim($part);
                if (filter_var($part, FILTER_VALIDATE_IP)) {
                    $ips[] = $part;
                }
            }
        }
        $dnsIps = gethostbynamel($hostname);
        if ($dnsIps) {
            foreach ($dnsIps as $dnsIp) {
                if (!in_array($dnsIp, $ips)) $ips[] = $dnsIp;
            }
        }
        return array_unique($ips);
    }

    public function checkDnsPropagation(string $domain = null): array
    {
        $domain = $domain ?? request()->getHost();
        $dnsServers = ['1.1.1.1', '8.8.8.8', '9.9.9.9'];
        $results = [];
        foreach ($dnsServers as $server) {
            $raw = @shell_exec("dig @{$server} A {$domain} +short 2>&1");
            $ips = array_filter(explode("\n", trim($raw ?? '')));
            $results[$server] = ['ips' => array_values($ips), 'count' => count($ips)];
        }
        $serverIps = $this->getServerIps();
        $exposed = false;
        foreach ($results as $dnsResult) {
            foreach ($dnsResult['ips'] as $ip) {
                if (in_array($ip, $serverIps)) { $exposed = true; break 2; }
            }
        }
        return [
            'domain' => $domain, 'server_ips' => $serverIps, 'dns_results' => $results,
            'real_ip_exposed' => $exposed,
            'verdict' => $exposed ? 'Real IP exposed via DNS! Enable orange cloud.' : 'Real IP hidden. DNS shows Cloudflare IPs only.',
        ];
    }

    private function fetchCfIps(): array
    {
        if (!empty($this->cachedCfIps)) return $this->cachedCfIps;
        try {
            $v4 = array_filter(explode("\n", trim(Http::get(self::CF_IPS_V4_URL)->body())));
            $v6 = array_filter(explode("\n", trim(Http::get(self::CF_IPS_V6_URL)->body())));
            $this->cachedCfIps = ['ipv4' => $v4, 'ipv6' => $v6];
            return $this->cachedCfIps;
        } catch (\Exception $e) {
            Log::error('OriginProtection: Failed to fetch CF IPs: ' . $e->getMessage());
            return ['ipv4' => [], 'ipv6' => []];
        }
    }

    public function getStealthStatus(string $domain = null): array
    {
        $domain = $domain ?? request()->getHost();
        $digA = @shell_exec("dig A {$domain} +short 2>&1");
        $digAAAA = @shell_exec("dig AAAA {$domain} +short 2>&1");
        $digMX = @shell_exec("dig MX {$domain} +short 2>&1");
        $digNS = @shell_exec("dig NS {$domain} +short 2>&1");
        $digCNAME = @shell_exec("dig CNAME {$domain} +short 2>&1");

        $aRecords = array_filter(explode("\n", trim($digA ?? '')));
        $aaaaRecords = array_filter(explode("\n", trim($digAAAA ?? '')));
        $mxRecords = array_filter(explode("\n", trim($digMX ?? '')));
        $nsRecords = array_filter(explode("\n", trim($digNS ?? '')));
        $cnameRecords = array_filter(explode("\n", trim($digCNAME ?? '')));

        $serverIps = $this->getServerIps();
        $realIpExposed = false;
        foreach ($aRecords as $ip) {
            if (in_array(trim($ip), $serverIps)) { $realIpExposed = true; break; }
        }

        $tunnelInstalled = $this->isCloudflareTunnelInstalled();
        $tunnelActive = $this->isCloudflareTunnelRunning();

        $stealthScore = 0;
        $stealthScore += $this->cloudflare->enabled() ? 2 : 0;
        $stealthScore += empty($aRecords) ? 2 : 0;
        $stealthScore += ($tunnelInstalled && $tunnelActive) ? 3 : 0;
        $stealthScore += !$realIpExposed ? 1 : 0;
        $stealthScore += !empty($cnameRecords) ? 1 : 0;
        $stealthScore += $this->isStealthModeEnabled() ? 2 : 0;

        $checks = [
            'has_a_record' => ['pass' => empty($aRecords), 'detail' => empty($aRecords) ? 'No A records (stealth)' : 'A records visible: ' . implode(', ', $aRecords)],
            'has_aaaa_record' => ['pass' => empty($aaaaRecords), 'detail' => empty($aaaaRecords) ? 'No AAAA records (stealth)' : 'AAAA records visible: ' . implode(', ', $aaaaRecords)],
            'real_ip_hidden' => ['pass' => !$realIpExposed, 'detail' => $realIpExposed ? 'Real IP ' . implode(', ', $serverIps) . ' exposed!' : 'Real IP not found in DNS'],
            'cloudflare_proxied' => ['pass' => $this->cloudflare->enabled(), 'detail' => $this->cloudflare->enabled() ? 'Cloudflare proxy available' : 'Cloudflare not configured'],
            'tunnel_active' => ['pass' => $tunnelInstalled && $tunnelActive, 'detail' => $tunnelActive ? 'Cloudflare Tunnel running' : ($tunnelInstalled ? 'cloudflared installed but not running' : 'cloudflared not installed')],
            'cname_setup' => ['pass' => !empty($cnameRecords), 'detail' => !empty($cnameRecords) ? 'CNAME: ' . implode(', ', $cnameRecords) : 'No CNAME - using A/AAAA directly'],
            'stealth_mode' => ['pass' => $this->isStealthModeEnabled(), 'detail' => $this->isStealthModeEnabled() ? 'Stealth mode enabled' : 'Stealth mode disabled'],
        ];

        return [
            'domain' => $domain, 'stealth_score' => $stealthScore, 'max_score' => 11,
            'stealth_level' => match (true) {
                $stealthScore >= 8 => 'Total Stealth',
                $stealthScore >= 5 => 'Partial Stealth',
                default => 'Visible',
            },
            'records' => ['A' => $aRecords, 'AAAA' => $aaaaRecords, 'MX' => $mxRecords, 'NS' => $nsRecords, 'CNAME' => $cnameRecords],
            'real_ip_exposed' => $realIpExposed, 'server_ips' => $serverIps, 'checks' => $checks,
        ];
    }

    public function enableStealthMode(string $domain = null): array
    {
        if (!$this->cloudflare->enabled()) return ['success' => false, 'error' => 'Cloudflare not configured'];
        $domain = $domain ?? request()->getHost();
        $results = [];
        $proxyResult = $this->cloudflare->setDnsProxy($domain, true);
        $results['orange_cloud'] = $proxyResult;
        $records = $this->cloudflare->getDnsRecords('A');
        if (($records['success'] ?? false) && !empty($records['result'])) {
            foreach ($records['result'] as $record) {
                $name = $record['name'] ?? '';
                $content = $record['content'] ?? '';
                $serverIps = $this->getServerIps();
                if (in_array($content, $serverIps)) {
                    $res = $this->cloudflare->setDnsProxy($name, true);
                    $results['a_records_proxied'][] = ['name' => $name, 'content' => $content, 'success' => $res['success'] ?? false];
                }
            }
        }
        $tunnelCmd = trim(shell_exec('which cloudflared 2>&1') ?? '');
        if (empty($tunnelCmd)) {
            $results['tunnel_guide'] = ['installed' => false, 'guide' => "Install tunnel:\n  curl -L https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -o /usr/local/bin/cloudflared\n  chmod +x /usr/local/bin/cloudflared\n  cloudflared tunnel login\n  cloudflared tunnel create royal\n  cloudflared tunnel route dns royal {$domain}"];
        } else {
            $results['tunnel_guide'] = ['installed' => true, 'message' => 'cloudflared installed. Run: cloudflared tunnel create <name> && cloudflared tunnel route dns <name> <domain>'];
        }
        $this->installCfOnlyIptables();
        $results['cf_only_iptables'] = true;
        $this->blockDirectIpAccess();
        $results['direct_ip_blocked'] = true;
        $this->installRealIpConfig();
        $results['real_ip_configured'] = true;
        $this->markStealthEnabled();
        return ['success' => true, 'domain' => $domain, 'results' => $results, 'message' => 'Stealth mode activated.'];
    }

    public function disableStealthMode(): array
    {
        $this->clearStealthMode();
        return ['success' => true, 'message' => 'Stealth mode disabled'];
    }

    public function showAllRecords(): array
    {
        if (!$this->cloudflare->enabled()) return ['success' => false, 'error' => 'Cloudflare not configured'];
        $records = $this->cloudflare->getDnsRecords();
        if (!($records['success'] ?? false)) return $records;
        $summary = [];
        foreach ($records['result'] ?? [] as $r) {
            $summary[] = ['name' => $r['name'] ?? '', 'type' => $r['type'] ?? '', 'content' => $r['content'] ?? '', 'proxied' => $r['proxied'] ? 'proxied' : 'dns-only'];
        }
        return ['success' => true, 'records' => $summary];
    }

    private function isCloudflareTunnelRunning(): bool
    {
        $ps = @shell_exec('ps aux | grep cloudflared | grep -v grep 2>&1');
        return !empty($ps);
    }

    private function isStealthModeEnabled(): bool
    {
        return file_exists(storage_path('app/security/stealth_mode.lock'));
    }

    private function markStealthEnabled(): void
    {
        $dir = storage_path('app/security');
        if (!is_dir($dir)) mkdir($dir, 0755, true);
        file_put_contents(storage_path('app/security/stealth_mode.lock'), json_encode(['enabled_at' => now()->toIso8601String()]));
    }

    private function clearStealthMode(): void
    {
        $lock = storage_path('app/security/stealth_mode.lock');
        if (file_exists($lock)) unlink($lock);
    }

    private function isCfIptablesInstalled(): bool
    {
        $raw = shell_exec('iptables -L INPUT -n 2>&1');
        return $raw !== null && str_contains($raw, 'cloudflare');
    }

    private function isCloudflareTunnelInstalled(): bool
    {
        $which = trim(shell_exec('which cloudflared 2>&1') ?? '');
        return !empty($which) && str_contains($which, 'cloudflared');
    }

    private function isDirectIpAccessBlocked(): bool
    {
        $raw = shell_exec('iptables -L INPUT -n 2>&1');
        return $raw !== null && str_contains($raw ?? '', 'DIRECTIP');
    }

    private function isRealIpConfigured(): bool
    {
        $cfConf = @file_get_contents('/etc/nginx/cloudflare.conf');
        return $cfConf !== false && str_contains($cfConf, 'CF-Connecting-IP');
    }
}
